### PR TITLE
[WIP] add security ruleset

### PR DESCRIPTION
**Pull request by omansour**

### CODE REVIEW

**Comment by mikaelrandy** [comment]
I just try to execute theses new standard on our internal project and i got the following results : 

```
./bin/coke

FILE: ...e/m6web/service-6play-notifier/src/NotifierBundle/Payload/Validator.php
--------------------------------------------------------------------------------
FOUND 0 ERROR(S) AND 2 WARNING(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
 45 | WARNING | Filesystem function file_exists() detected with dynamic
    |         | parameter
 48 | WARNING | Filesystem function file_get_contents() detected with dynamic
    |         | parameter
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------

[FAIL] Some files do not match with "vendor/m6web/symfony2-coding-standard/Symfony2,vendor/m6web/symfony2-coding-standard/Security" requirements
```

That's right, we use dynamic parameters for these 2 functions, but i think it should not be a WARNING, because this way of using dynamic parameters could be totally secure.
For me, its should be NOTICE, not WARNING.

To conclude, in the actual state, the standard is too restrictive to be applied automatically.

**Comment by omansour** [comment]
can you test with the last version ?

**Comment by mguillermin** [comment]
I've just tested it on a few projects. 

On some projects, I've got fatal errors : 
```
PHP Fatal error:  Call to undefined method PHP_CodeSniffer_File::addNotice() in /.../vendor/m6web/symfony2-coding-standard/Security/Sniffs/BadFunctions/FilesystemFunctionsSniff.php on line 48
```

I also have warnings with the use of functions accepting callbacks like `usort` or `array_map`. I might be wrong but I don't think these warnings are relevant.
```
--------------------------------------------------------------------------------
FOUND 0 ERROR(S) AND 1 WARNING(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 190 | WARNING | Function usort() that supports callback detected
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
FOUND 0 ERROR(S) AND 1 WARNING(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 20 | WARNING | Function array_map() that supports callback detected
--------------------------------------------------------------------------------
```

**Comment by mikaelrandy** [comment]
i just retry the same coke execution on the same project and now, it's okay for me

**Comment by valentin-claras** [comment]
Still relevant? @omansour @mikaelrandy

**Pull request closed without merging**
